name: Server

on:
  push:
    branches:
      - master
    paths:
      - server


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: set remote
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: git:remote -a frontier-server
    - name: push
      run: |
        git config --get remote.heroku.url
        git subtree push --prefix server heroku master
